blank_issues_enabled: true
contact_links:
  - name: Community Support
    url: https://github.com/justinmak08, EricYangg, Maple018, Olytics/sudoku_validation/discussions
    about: Please ask and answer questions here.
