name: Build and Test
# Run the test suite and style checkers on pull requests and pushes to main branch
on:
  pull_request:
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v4.5.2

    - name: Set up Python
      uses: actions/setup-python@e797f83bcb11b83ae66e0230d6156d7c80228e7c # v5.1.0
      with:
        python-version: "3.10"
    - name: Install hatch
      run: |
        python -m pip install --upgrade pip
        python -m pip install hatch
    - name: Run test suite
      run: hatch run +py=3.10 test:run
    - name: Run style checkers
      run: |
        python -m pip install ruff
        ruff check src/ tests/
